import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { VRMLoaderPlugin, VRMUtils } from '@pixiv/three-vrm';

const DEFAULT={coins:1250,owned:['starter_top','starter_bottom','starter_shoes'],equipped:{top:'starter_top',bottom:'starter_bottom',shoes:'starter_shoes',background:'bg_sky'}};
const ITEMS=[
{id:'starter_top',cat:'Tops',name:'Starter T-Shirt',icon:'👕',price:0,desc:'Your basic Level 1 top.'},
{id:'blue_hoodie',cat:'Tops',name:'Blue Hoodie',icon:'🧥',price:350,desc:'A cool reward for regular practice.'},
{id:'english_hoodie',cat:'Tops',name:'English Hoodie',icon:'🎽',price:600,desc:'Premium English learner hoodie.'},
{id:'starter_bottom',cat:'Bottoms',name:'Starter Pants',icon:'👖',price:0,desc:'Simple beginner pants.'},
{id:'cargo_pants',cat:'Bottoms',name:'Cargo Pants',icon:'👖',price:400,desc:'Street-style cargo pants.'},
{id:'starter_shoes',cat:'Shoes',name:'Starter Sneakers',icon:'👟',price:0,desc:'Basic everyday sneakers.'},
{id:'runner_shoes',cat:'Shoes',name:'Runner Sneakers',icon:'👟',price:300,desc:'Sporty reward sneakers.'},
{id:'headphones',cat:'Accessories',name:'Headphones',icon:'🎧',price:450,desc:'Study-music style accessory.'},
{id:'backpack',cat:'Accessories',name:'Backpack',icon:'🎒',price:500,desc:'Ready for English class.'},
{id:'bg_sky',cat:'Backgrounds',name:'Sky Classroom',icon:'🌤️',price:0,desc:'Bright beginner background.'},
{id:'bg_sunset',cat:'Backgrounds',name:'Sunset',icon:'🌅',price:250,desc:'Warm after-school atmosphere.'},
{id:'bg_night',cat:'Backgrounds',name:'Night Study',icon:'🌙',price:300,desc:'A calm night-study scene.'}
];
const SLOT={Tops:'top',Bottoms:'bottom',Shoes:'shoes',Backgrounds:'background'};
let state=loadState(),activeCat='Tops',mode='shop';
function loadState(){try{const s=JSON.parse(localStorage.getItem('moeStep3'));return {...DEFAULT,...s,equipped:{...DEFAULT.equipped,...(s?.equipped||{})},owned:Array.from(new Set([...(s?.owned||[]),...DEFAULT.owned]))}}catch{return structuredClone(DEFAULT)}}
function save(){localStorage.setItem('moeStep3',JSON.stringify(state));updateUI()}
function fmt(n){return Number(n).toLocaleString()}
function item(id){return ITEMS.find(x=>x.id===id)}
function isEquipped(i){if(i.cat==='Accessories')return (state.equipped.accessories||[]).includes(i.id);return state.equipped[SLOT[i.cat]]===i.id}
function toast(t){const e=document.querySelector('#toast');e.textContent=t;e.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.add('hidden'),1800)}
function updateUI(){document.querySelectorAll('.coinCount').forEach(e=>e.textContent=fmt(state.coins));document.querySelector('#ownedCount').textContent=state.owned.length;const list=document.querySelector('#equippedList');const ids=[state.equipped.top,state.equipped.bottom,state.equipped.shoes,state.equipped.background,...(state.equipped.accessories||[])].filter(Boolean);list.innerHTML=ids.map(id=>{const i=item(id);return i?`<div class="equip-row"><span class="equip-icon">${i.icon}</span><div><strong>${i.name}</strong><small>${i.cat}</small></div></div>`:''}).join('');applyBackground();if(!document.querySelector('#overlay').classList.contains('hidden'))renderItems()}
function applyBackground(){const id=state.equipped.background;let c=0xcfefff,f=0xcfefff;if(id==='bg_sunset'){c=0xffdfbd;f=0xffdfbd}if(id==='bg_night'){c=0x193453;f=0x193453}scene.background=new THREE.Color(c);scene.fog.color=new THREE.Color(f)}
function openModal(which){mode=which;document.querySelector('#overlay').classList.remove('hidden');document.querySelector('#modalEyebrow').textContent=which==='shop'?'REWARD SHOP':'YOUR COLLECTION';document.querySelector('#modalTitle').textContent=which==='shop'?'Shop':'Inventory';renderTabs();renderItems()}
function renderTabs(){const cats=['Tops','Bottoms','Shoes','Accessories','Backgrounds'];document.querySelector('#categoryTabs').innerHTML=cats.map(c=>`<button class="tab ${c===activeCat?'active':''}" data-cat="${c}">${c}</button>`).join('');document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{activeCat=b.dataset.cat;renderTabs();renderItems()})}
function renderItems(){let arr=ITEMS.filter(i=>i.cat===activeCat);if(mode==='inventory')arr=arr.filter(i=>state.owned.includes(i.id));const grid=document.querySelector('#itemGrid');if(!arr.length){grid.innerHTML='<p>Your collection is empty in this category.</p>';return}grid.innerHTML=arr.map(i=>{const owned=state.owned.includes(i.id),eq=isEquipped(i);let label=owned?(eq?'Equipped':'Equip'):`🪙 ${fmt(i.price)}`;let disabled=eq||(!owned&&state.coins<i.price);return `<article class="item-card ${eq?'equipped':''}">${owned?'<span class="owned-tag">OWNED</span>':''}<div class="item-art">${i.icon}</div><h3>${i.name}</h3><p>${i.desc}</p><div class="item-meta"><span class="price">${owned?'✓ In collection':'🪙 '+fmt(i.price)}</span><button class="buy-btn ${owned?'equip':''}" data-item="${i.id}" ${disabled?'disabled':''}>${label}</button></div></article>`}).join('');document.querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>act(item(b.dataset.item)))}
function act(i){const owned=state.owned.includes(i.id);if(!owned){if(state.coins<i.price)return;state.coins-=i.price;state.owned.push(i.id);toast(`${i.name} purchased!`)}if(i.cat==='Accessories'){state.equipped.accessories=state.equipped.accessories||[];if(!state.equipped.accessories.includes(i.id))state.equipped.accessories.push(i.id)}else state.equipped[SLOT[i.cat]]=i.id;save();toast(`${i.name} equipped!`)}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{if(b.dataset.page==='shop'||b.dataset.page==='inventory')openModal(b.dataset.page)});document.querySelector('#closeModal').onclick=()=>document.querySelector('#overlay').classList.add('hidden');document.querySelector('#overlay').onclick=e=>{if(e.target.id==='overlay')e.currentTarget.classList.add('hidden')};

const viewer=document.querySelector('#viewer'),loading=document.querySelector('#loading'),errorBox=document.querySelector('#errorBox'),statusCard=document.querySelector('#modelStatus');
const scene=new THREE.Scene();scene.background=new THREE.Color(0xcfefff);scene.fog=new THREE.Fog(0xcfefff,8,16);const camera=new THREE.PerspectiveCamera(30,1,.1,100);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=true;viewer.appendChild(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.075;controls.enablePan=true;controls.screenSpacePanning=true;controls.minDistance=1.25;controls.maxDistance=5.5;scene.add(new THREE.HemisphereLight(0xffffff,0x7898ad,2.15));const key=new THREE.DirectionalLight(0xffffff,2.4);key.position.set(3.5,5,4);key.castShadow=true;scene.add(key);const fill=new THREE.DirectionalLight(0xd5edff,1.4);fill.position.set(-4,3,2);scene.add(fill);const floor=new THREE.Mesh(new THREE.CircleGeometry(1.22,72),new THREE.MeshStandardMaterial({color:0xe2e9ed,roughness:.8}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);let currentVRM=null,modelHeight=1.8;
function setStatus(kind,title,detail){statusCard.classList.remove('ready','error-state');if(kind==='ready')statusCard.classList.add('ready');if(kind==='error')statusCard.classList.add('error-state');statusCard.querySelector('strong').textContent=title;statusCard.querySelector('small').textContent=detail}
function fitModel(model){model.updateMatrixWorld(true);let box=new THREE.Box3().setFromObject(model),size=box.getSize(new THREE.Vector3());if(size.y>0)model.scale.multiplyScalar(1.82/size.y);model.updateMatrixWorld(true);box=new THREE.Box3().setFromObject(model);size=box.getSize(new THREE.Vector3());const center=box.getCenter(new THREE.Vector3());model.position.x-=center.x;model.position.z-=center.z;model.position.y-=box.min.y;modelHeight=size.y;setView('front',false)}
function setView(v,buttons=true){const d=Math.max(2.7,modelHeight*1.72),y=Math.max(1.05,modelHeight*.58),ty=Math.max(.92,modelHeight*.52);controls.target.set(0,ty,0);if(v==='front')camera.position.set(0,y,d);if(v==='back')camera.position.set(0,y,-d);if(v==='left')camera.position.set(-d,y,0);if(v==='right')camera.position.set(d,y,0);camera.lookAt(controls.target);controls.update();if(buttons)document.querySelectorAll('.view-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===v))}
const loader=new GLTFLoader();loader.register(p=>new VRMLoaderPlugin(p));loader.load('./assets/moe-beginner.vrm?v=5',gltf=>{currentVRM=gltf.userData.vrm;if(!currentVRM)throw Error('No VRM data');VRMUtils.rotateVRM0(currentVRM);scene.add(currentVRM.scene);currentVRM.scene.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;o.frustumCulled=false}});fitModel(currentVRM.scene);loading.classList.add('hidden');setStatus('ready','Beginner avatar loaded!','Shop data is ready and saved locally.')},p=>{if(p.total)loading.querySelector('span').textContent=`${Math.min(100,Math.round(p.loaded/p.total*100))}% loaded`},err=>{console.error(err);loading.classList.add('hidden');setStatus('error','Model could not load','Check assets/moe-beginner.vrm');errorBox.textContent='The local VRM could not load.';errorBox.classList.remove('hidden')});
document.querySelector('#resetBtn').onclick=()=>setView('front');document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));function resize(){const w=Math.max(1,viewer.clientWidth),h=Math.max(1,viewer.clientHeight);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();const clock=new THREE.Clock();renderer.setAnimationLoop(()=>{const d=Math.min(clock.getDelta(),.05);if(currentVRM)currentVRM.update(d);controls.update();renderer.render(scene,camera)});updateUI();
