const $=id=>document.getElementById(id);
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
const norm=s=>s.toLowerCase().trim().replace(/[’']/g,"'").replace(/\s+/g," ");
let grade=null,unit=null,words=[],xp=Number(localStorage.getItem("portalXP")||0);
let studied=new Set(),favorites=new Set(),wrong=new Set();
let quizItems=[],quizIndex=0,quizScore=0,spellItems=[],spellIndex=0,spellScore=0;
let fillItems=[],fillIndex=0,fillScore=0,speedTimer=null,speedCurrent=null,speedPoints=0,speedSeconds=30;
const colors=["#ffdada","#dcecff","#e3f4db","#fff0c8","#eadcff","#d9f3ef","#ffe2ef","#e9e3ff"];

function showView(id){document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));$(id).classList.add("active")}
function saveSets(){localStorage.setItem(`studied-${grade}-${unit}`,JSON.stringify([...studied]));localStorage.setItem(`favorites-${grade}-${unit}`,JSON.stringify([...favorites]));localStorage.setItem(`wrong-${grade}-${unit}`,JSON.stringify([...wrong]))}
function loadSets(){studied=new Set(JSON.parse(localStorage.getItem(`studied-${grade}-${unit}`)||"[]"));favorites=new Set(JSON.parse(localStorage.getItem(`favorites-${grade}-${unit}`)||"[]"));wrong=new Set(JSON.parse(localStorage.getItem(`wrong-${grade}-${unit}`)||"[]"))}
function addXP(n){xp+=n;localStorage.setItem("portalXP",xp);updateStats();toast(`+${n} XP`)}
function updateStats(){$("xpValue").textContent=xp;$("levelValue").textContent=Math.floor(xp/250)+1;$("studiedCount").textContent=studied.size;$("favoriteCount").textContent=favorites.size;$("wrongCount").textContent=wrong.size;$("progressText").textContent=`${studied.size} of ${words.length} words studied`;$("progressBar").style.width=`${words.length?studied.size/words.length*100:0}%`}
function toast(msg){const t=$("toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1100)}
function speak(text){if(!window.speechSynthesis||$("soundBtn").dataset.off==="1")return;const u=new SpeechSynthesisUtterance(text);u.lang="en-US";speechSynthesis.cancel();speechSynthesis.speak(u)}
function markStudied(w){studied.add(w);saveSets();updateStats()}
function markWrong(w){wrong.add(w);saveSets();updateStats()}
function clearWrongWord(w){wrong.delete(w);saveSets();updateStats()}

function goHome(){showView("homeView")}
function openGrade(g){grade=g;const d=PORTAL_DATA[g];$("gradeLabel").textContent=d.label.toUpperCase();$("gradeTitle").textContent=d.title;$("unitGrid").innerHTML="";for(let i=1;i<=10;i++){const u=d.units[i],b=document.createElement("button");b.className="unit-card"+(u?"":" locked");b.innerHTML=`<span class="badge">${u?"AVAILABLE":"COMING SOON"}</span><h3>Unit ${i}</h3><p>${u?u.subtitle:"Vocabulary will be added later."}</p>`;if(u)b.onclick=()=>openUnit(i);$("unitGrid").appendChild(b)}showView("unitsView")}
function openUnit(n){unit=n;const d=PORTAL_DATA[grade].units[n];words=d.words;loadSets();$("studyLabel").textContent=`${grade.toUpperCase()} · ${PORTAL_DATA[grade].label.toUpperCase()}`;$("studyTitle").textContent=`${d.title} Vocabularies (単語)`;$("studySubtitle").textContent=d.subtitle;$("wordCount").textContent=words.length;renderFlashcards(words,$("flashcardGrid"));updateStats();switchMode("flashcards");showView("studyView")}

function renderFlashcards(arr,container){container.innerHTML="";if(!arr.length){container.innerHTML="<p>No words saved here yet.</p>";return}arr.forEach((x,i)=>{const card=document.createElement("div");card.className="flashcard";const fav=favorites.has(x[0]);card.innerHTML=`<button class="favorite-star" title="Favorite">${fav?"⭐":"☆"}</button><div class="flash-inner"><div class="flash-face" style="background:${colors[i%colors.length]}"><div class="flash-emoji">${x[2]||"📝"}</div><div class="flash-word">${x[0]}</div></div><div class="flash-face flash-back" style="background:${colors[(i+3)%colors.length]}"><div class="flash-word">${x[1]}</div><small>${x[3]||""}</small></div></div>`;card.querySelector(".favorite-star").onclick=e=>{e.stopPropagation();favorites.has(x[0])?favorites.delete(x[0]):favorites.add(x[0]);saveSets();updateStats();renderFlashcards(arr,container)};card.onclick=()=>{card.classList.toggle("flipped");markStudied(x[0]);speak(x[0])};container.appendChild(card)})}

function switchMode(id){document.querySelectorAll(".mode-btn").forEach(b=>b.classList.toggle("active",b.dataset.mode===id));document.querySelectorAll(".game").forEach(g=>g.classList.toggle("active",g.id===id));if(id==="quiz")startQuiz();if(id==="spelling")startSpelling();if(id==="matching")startMatching();if(id==="memory")startMemory();if(id==="hangman")startHangman();if(id==="fillblank")startFill();if(id==="favorites")renderFlashcards(words.filter(w=>favorites.has(w[0])),$("favoriteGrid"));if(id==="wrong")renderFlashcards(words.filter(w=>wrong.has(w[0])),$("wrongGrid"))}

function startQuiz(){quizItems=shuffle(words).slice(0,Math.min(10,words.length));quizIndex=0;quizScore=0;renderQuiz()}
function renderQuiz(){const c=quizItems[quizIndex];if(!c){$("quizPrompt").textContent=`Finished! ${quizScore} / ${quizItems.length}`;$("quizChoices").innerHTML="";$("quizFeedback").textContent="Great job!";$("quizNextBtn").classList.add("hidden");return}$("quizProgress").textContent=`Question ${quizIndex+1} / ${quizItems.length}`;$("quizScore").textContent=`Score: ${quizScore}`;$("quizPrompt").textContent=c[1];$("quizFeedback").textContent="";$("quizNextBtn").classList.add("hidden");$("quizChoices").innerHTML="";const opts=shuffle([c,...shuffle(words.filter(x=>x[0]!==c[0])).slice(0,3)]);opts.forEach(o=>{const b=document.createElement("button");b.className="choice";b.textContent=o[0];b.onclick=()=>{document.querySelectorAll("#quizChoices .choice").forEach(x=>x.disabled=true);if(o[0]===c[0]){b.classList.add("correct");quizScore++;addXP(10);markStudied(c[0]);clearWrongWord(c[0]);$("quizFeedback").textContent="Correct! 正解！";speak(c[0])}else{b.classList.add("wrong");markWrong(c[0]);$("quizFeedback").textContent=`Answer: ${c[0]}`}$("quizScore").textContent=`Score: ${quizScore}`;$("quizNextBtn").classList.remove("hidden")};$("quizChoices").appendChild(b)})}

function startSpelling(){spellItems=shuffle(words).slice(0,Math.min(10,words.length));spellIndex=0;spellScore=0;renderSpelling()}
function renderSpelling(){const c=spellItems[spellIndex];if(!c){$("spellPrompt").textContent=`Finished! ${spellScore} / ${spellItems.length}`;$("spellInput").disabled=true;$("spellCheckBtn").disabled=true;$("spellNextBtn").classList.add("hidden");return}$("spellProgress").textContent=`Word ${spellIndex+1} / ${spellItems.length}`;$("spellScore").textContent=`Score: ${spellScore}`;$("spellPrompt").textContent=c[1];$("spellInput").value="";$("spellInput").disabled=false;$("spellCheckBtn").disabled=false;$("spellFeedback").textContent="";$("spellNextBtn").classList.add("hidden");$("spellInput").focus()}
function checkSpelling(){const c=spellItems[spellIndex];if(!c)return;const ok=norm($("spellInput").value)===norm(c[0]);$("spellInput").disabled=true;$("spellCheckBtn").disabled=true;if(ok){spellScore++;addXP(12);markStudied(c[0]);clearWrongWord(c[0]);$("spellFeedback").textContent="Correct! 正解！";speak(c[0])}else{markWrong(c[0]);$("spellFeedback").textContent=`Answer: ${c[0]}`}$("spellScore").textContent=`Score: ${spellScore}`;$("spellNextBtn").classList.remove("hidden")}

function startMatching(){const round=shuffle(words).slice(0,Math.min(6,words.length)),eng=round.map((x,i)=>({text:x[0],id:i,word:x[0]})),jpn=shuffle(round.map((x,i)=>({text:x[1],id:i,word:x[0]})));$("matchingBoard").innerHTML='<div id="engCol" class="match-column"></div><div id="jpnCol" class="match-column"></div>';let a=null,b=null,count=0;const check=()=>{if(!a||!b)return;if(a.dataset.id===b.dataset.id){a.classList.add("matched");b.classList.add("matched");count++;$("matchingCount").textContent=`${count} / ${round.length}`;addXP(8);markStudied(a.dataset.word)}else{setTimeout(()=>{a?.classList.remove("selected");b?.classList.remove("selected");a=b=null},250);return}a.classList.remove("selected");b.classList.remove("selected");a=b=null};eng.forEach(x=>{const c=document.createElement("button");c.className="match-item";c.textContent=x.text;c.dataset.id=x.id;c.dataset.word=x.word;c.onclick=()=>{document.querySelectorAll("#engCol .match-item").forEach(e=>e.classList.remove("selected"));a=c;c.classList.add("selected");check()};$("engCol").appendChild(c)});jpn.forEach(x=>{const c=document.createElement("button");c.className="match-item";c.textContent=x.text;c.dataset.id=x.id;c.dataset.word=x.word;c.onclick=()=>{document.querySelectorAll("#jpnCol .match-item").forEach(e=>e.classList.remove("selected"));b=c;c.classList.add("selected");check()};$("jpnCol").appendChild(c)});$("matchingCount").textContent=`0 / ${round.length}`}

function startMemory(){const round=shuffle(words).slice(0,Math.min(6,words.length));const cards=shuffle(round.flatMap((x,i)=>[{text:x[0],id:i,word:x[0]},{text:x[1],id:i,word:x[0]}]));$("memoryBoard").innerHTML="";let first=null,lock=false,count=0;cards.forEach(x=>{const b=document.createElement("button");b.className="memory-card";b.textContent="?";b.dataset.id=x.id;b.dataset.text=x.text;b.dataset.word=x.word;b.onclick=()=>{if(lock||b.classList.contains("matched")||b===first)return;b.textContent=b.dataset.text;b.classList.add("revealed");if(!first){first=b;return}if(first.dataset.id===b.dataset.id){first.classList.add("matched");b.classList.add("matched");count++;$("memoryCount").textContent=`${count} / ${round.length}`;addXP(10);markStudied(b.dataset.word);first=null}else{lock=true;setTimeout(()=>{first.textContent="?";b.textContent="?";first.classList.remove("revealed");b.classList.remove("revealed");first=null;lock=false},650)}};$("memoryBoard").appendChild(b)});$("memoryCount").textContent=`0 / ${round.length}`}

function startSpeed(){clearInterval(speedTimer);speedSeconds=30;speedPoints=0;$("speedTime").textContent=speedSeconds;$("speedScore").textContent="Score: 0";$("speedStartBtn").classList.add("hidden");nextSpeed();speedTimer=setInterval(()=>{speedSeconds--;$("speedTime").textContent=speedSeconds;if(speedSeconds<=0){clearInterval(speedTimer);$("speedPrompt").textContent=`Finished! Score: ${speedPoints}`;$("speedChoices").innerHTML="";$("speedStartBtn").classList.remove("hidden")}},1000)}
function nextSpeed(){speedCurrent=shuffle(words)[0];$("speedPrompt").textContent=speedCurrent[1];$("speedChoices").innerHTML="";shuffle([speedCurrent,...shuffle(words.filter(x=>x[0]!==speedCurrent[0])).slice(0,3)]).forEach(o=>{const b=document.createElement("button");b.className="choice";b.textContent=o[0];b.onclick=()=>{if(o[0]===speedCurrent[0]){speedPoints++;addXP(3);markStudied(speedCurrent[0]);clearWrongWord(speedCurrent[0])}else{markWrong(speedCurrent[0])}$("speedScore").textContent=`Score: ${speedPoints}`;nextSpeed()};$("speedChoices").appendChild(b)})}

function startHangman(){const c=shuffle(words)[0],answer=c[0].toLowerCase();let guessed=new Set(),mistakes=0;$("hangmanMeaning").textContent=c[1];$("hangmanFeedback").textContent="";$("hangmanLetters").innerHTML="";const display=()=>{$("hangmanWord").textContent=[...answer].map(ch=>/[a-z]/.test(ch)?(guessed.has(ch)?ch:"_"):ch).join(" ");$("hangmanMistakes").textContent=mistakes;const won=[...answer].every(ch=>!/[a-z]/.test(ch)||guessed.has(ch));if(won){$("hangmanFeedback").textContent="You got it!";addXP(15);markStudied(c[0]);clearWrongWord(c[0]);document.querySelectorAll("#hangmanLetters button").forEach(b=>b.disabled=true)}if(mistakes>=6){$("hangmanFeedback").textContent=`Answer: ${c[0]}`;markWrong(c[0]);document.querySelectorAll("#hangmanLetters button").forEach(b=>b.disabled=true)}};"ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("").forEach(letter=>{const b=document.createElement("button");b.textContent=letter;b.onclick=()=>{b.disabled=true;const ch=letter.toLowerCase();guessed.add(ch);if(!answer.includes(ch))mistakes++;display()};$("hangmanLetters").appendChild(b)});display()}

function startFill(){fillItems=shuffle(words.filter(w=>w[3])).slice(0,Math.min(10,words.length));fillIndex=0;fillScore=0;renderFill()}
function renderFill(){const c=fillItems[fillIndex];if(!c){$("fillPrompt").textContent=`Finished! ${fillScore} / ${fillItems.length}`;$("fillInput").disabled=true;$("fillCheckBtn").disabled=true;$("fillNextBtn").classList.add("hidden");return}const escaped=c[0].replace(/[.*+?^${}()|[\]\\]/g,"\\$&");$("fillPrompt").textContent=c[3].replace(new RegExp(escaped,"i"),"_____");$("fillProgress").textContent=`Sentence ${fillIndex+1} / ${fillItems.length}`;$("fillScore").textContent=`Score: ${fillScore}`;$("fillInput").value="";$("fillInput").disabled=false;$("fillCheckBtn").disabled=false;$("fillFeedback").textContent="";$("fillNextBtn").classList.add("hidden")}
function checkFill(){const c=fillItems[fillIndex];if(!c)return;const ok=norm($("fillInput").value)===norm(c[0]);$("fillInput").disabled=true;$("fillCheckBtn").disabled=true;if(ok){fillScore++;addXP(12);markStudied(c[0]);clearWrongWord(c[0]);$("fillFeedback").textContent="Correct! 正解！"}else{markWrong(c[0]);$("fillFeedback").textContent=`Answer: ${c[0]}`}$("fillScore").textContent=`Score: ${fillScore}`;$("fillNextBtn").classList.remove("hidden")}

document.querySelectorAll(".grade-card").forEach(b=>b.onclick=()=>openGrade(b.dataset.grade));
$("logoBtn").onclick=goHome;$("backHomeBtn").onclick=goHome;$("backUnitsBtn").onclick=()=>openGrade(grade);
document.querySelectorAll(".mode-btn").forEach(b=>b.onclick=()=>switchMode(b.dataset.mode));
$("shuffleCardsBtn").onclick=()=>renderFlashcards(shuffle(words),$("flashcardGrid"));
$("quizNextBtn").onclick=()=>{quizIndex++;renderQuiz()};
$("spellCheckBtn").onclick=checkSpelling;$("spellInput").addEventListener("keydown",e=>{if(e.key==="Enter"&&!$("spellCheckBtn").disabled)checkSpelling()});$("spellNextBtn").onclick=()=>{spellIndex++;renderSpelling()};
$("newMatchingBtn").onclick=startMatching;$("newMemoryBtn").onclick=startMemory;
$("speedStartBtn").onclick=startSpeed;$("newHangmanBtn").onclick=startHangman;
$("fillCheckBtn").onclick=checkFill;$("fillInput").addEventListener("keydown",e=>{if(e.key==="Enter"&&!$("fillCheckBtn").disabled)checkFill()});$("fillNextBtn").onclick=()=>{fillIndex++;renderFill()};
$("clearWrongBtn").onclick=()=>{wrong.clear();saveSets();updateStats();renderFlashcards([],$("wrongGrid"))};
$("soundBtn").onclick=()=>{const off=$("soundBtn").dataset.off==="1";$("soundBtn").dataset.off=off?"0":"1";$("soundBtn").textContent=off?"🔊":"🔇"};
$("themeBtn").onclick=()=>{document.body.classList.toggle("dark");$("themeBtn").textContent=document.body.classList.contains("dark")?"🌙":"☀️"};
updateStats();